# Generated by Django 4.2 on 2025-06-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_apikey_toolconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
    ]
