# Generated by Django 4.2 on 2025-02-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(unique=True)),
                ('scrape_interval_value', models.PositiveIntegerField(default=1, help_text='Numeric value to indicate scraping interval.')),
                ('scrape_interval_unit', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes')], default='days', help_text='Unit of time for the scraping interval.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable scraping.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped', models.DateTimeField(blank=True, help_text='Timestamp of the last successful scrape.', null=True)),
                ('next_scheduled', models.DateTimeField(blank=True, help_text='Timestamp of the next scheduled scrape.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSourceScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('items_scraped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('content_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contentsource')),
            ],
        ),
    ]
