# Generated by Django 4.2 on 2025-02-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_name'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsource',
            name='url',
        ),
        migrations.AddField(
            model_name='contentsource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_sources', to='base.category'),
        ),
        migrations.CreateModel(
            name='ContentSourceURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('content_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='content.contentsource')),
            ],
        ),
    ]
