# Generated by Django 4.2 on 2025-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentsource_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
