# Generated by Django 4.2 on 2025-02-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-id']},
        ),
    ]
