# Generated by Django 4.2 on 2025-03-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_content_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='content.content')),
            ],
        ),
    ]
