# Generated by Django 4.2 on 2025-03-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_structuredinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredinsight',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuredinsight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
