# Generated by Django 4.2 on 2025-03-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_structuredinsight_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
