# Generated by Django 4.2 on 2025-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredinsight',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
