# Generated by Django 4.2 on 2025-03-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_structuredinsight_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredinsight',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='content.content'),
        ),
    ]
