# Generated by Django 4.2 on 2025-03-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_created_at_category_sort_order_and_more'),
        ('content', '0012_alter_structuredinsight_options_urltoscrape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='base.category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='original_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
