# Generated by Django 4.2 on 2025-03-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_content_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('topic', models.CharField(max_length=255)),
                ('query', models.TextField()),
                ('generated_report', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
