# Generated by Django 4.2 on 2025-03-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_domain', models.CharField(help_text='The base domain (e.g., google.com)', max_length=255, unique=True)),
                ('source', models.CharField(help_text='Type of source (e.g., University, Private company)', max_length=100)),
                ('authority', models.CharField(help_text='Level of authority (e.g., University, Government)', max_length=50)),
                ('data_origin', models.CharField(help_text='Origin of the data (e.g., Curated academic data)', max_length=255)),
                ('transparency', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='Transparency level of the source', max_length=20)),
                ('bias_risk', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='Risk of bias in the content', max_length=20)),
                ('peer_review', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='Level of peer review', max_length=20)),
                ('updated', models.BooleanField(default=False, help_text='Whether the content is regularly updated')),
                ('domain_authority_score', models.IntegerField(default=0, help_text='Initial score based on domain type (0-3)')),
                ('security_score', models.IntegerField(default=0, help_text='Score for HTTPS usage (0-1)')),
                ('recency_score', models.IntegerField(default=0, help_text='Score based on content age (0-3)')),
                ('content_quality_score', models.IntegerField(default=0, help_text='Score based on content length and quality (0-3)')),
                ('total_score', models.IntegerField(default=0, help_text='Total validity score (0-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
    ]
