# Generated by Django 4.2 on 2025-03-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_websiteevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredinsight',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='content.content'),
        ),
    ]
