# Generated by Django 4.2 on 2025-03-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_structuredinsight_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='thoughts',
            field=models.JSONField(default=list),
        ),
    ]
