# Generated by Django 4.2 on 2025-03-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_report_thoughts'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
