# Generated by Django 4.2 on 2025-03-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='content.prompt'),
        ),
    ]
