# Generated by Django 4.2 on 2025-03-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_report_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='topic',
            field=models.TextField(),
        ),
    ]
