# Generated by Django 4.2 on 2025-04-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_alter_scrapedurl_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedusecase',
            name='source',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedurl',
            name='url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
