# Generated by Django 4.2 on 2025-04-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_alter_extractedusecase_source_alter_scrapedurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedusecase',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='content.report'),
        ),
    ]
