# Generated by Django 4.2 on 2025-04-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_alter_extractedusecase_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedusecase',
            name='numerical_impact',
        ),
        migrations.AddField(
            model_name='extractedusecase',
            name='impact',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='extractedusecase',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='extractedusecase',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
