# Generated by Django 4.2 on 2025-04-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_remove_extractedusecase_numerical_impact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedusecase',
            name='benefits',
        ),
    ]
