# Generated by Django 4.2 on 2025-04-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_remove_extractedusecase_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedSDLCUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('industry_segment', models.CharField(blank=True, max_length=255)),
                ('sdlc_tools', models.TextField()),
                ('use_case_description', models.TextField()),
                ('metric_impact', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('credibility_score', models.FloatField(default=3.0)),
                ('source', models.URLField()),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sldc_use_cases', to='content.report')),
            ],
        ),
    ]
