# Generated by Django 4.2 on 2025-04-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_extractedsdlcusecase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedsdlcusecase',
            name='company',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='extractedsdlcusecase',
            name='industry_segment',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='extractedsdlcusecase',
            name='metric_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedsdlcusecase',
            name='source',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='extractedsdlcusecase',
            name='source_title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
