# Generated by Django 4.2 on 2025-04-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_alter_extractedsdlcusecase_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedsdlcusecase',
            name='source_title',
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
