# Generated by Django 4.2 on 2025-04-14 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_remove_extractedsdlcusecase_source_title_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedusecase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
