# Generated by Django 4.2 on 2025-04-15 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_extractedusecase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedusecase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ExtractedAISDLCUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, max_length=100, null=True)),
                ('use_case_description', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('performance_improvement', models.TextField(blank=True, null=True)),
                ('source', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sdlc_use_cases', to='content.report')),
            ],
            options={
                'verbose_name': 'Extracted AI SDLC Use Case',
                'verbose_name_plural': 'Extracted AI SDLC Use Cases',
            },
        ),
    ]
