# Generated by Django 4.2 on 2025-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_alter_extractedusecase_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractedaisdlcusecase',
            old_name='use_case_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='extractedaisdlcusecase',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedaisdlcusecase',
            name='use_case',
            field=models.TextField(blank=True, null=True),
        ),
    ]
