# Generated by Django 4.2 on 2025-04-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_rename_use_case_description_extractedaisdlcusecase_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractedaisdlcusecase',
            old_name='performance_improvement',
            new_name='performance_improvements',
        ),
    ]
