# Generated by Django 4.2 on 2025-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_rename_performance_improvement_extractedaisdlcusecase_performance_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedaisdlcusecase',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
