# Generated by Django 4.2 on 2025-05-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_alter_extractedaisdlcusecase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedsdlcusecase',
            name='credibility_score',
        ),
    ]
