# Generated by Django 4.2 on 2025-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_remove_extractedsdlcusecase_credibility_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedaisdlcusecase',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
