# Generated by Django 4.2 on 2025-05-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_extractedaisdlcusecase_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedsdlcusecase',
            name='phase',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
