# Generated by Django 4.2 on 2025-05-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_extractedsdlcusecase_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case_type', models.CharField(blank=True, max_length=400, null=True)),
                ('company', models.CharField(max_length=400)),
                ('industry', models.CharField(blank=True, max_length=400, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('use_case_description', models.TextField()),
                ('performance_impact', models.TextField(blank=True, null=True)),
                ('use_case_date', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cases', to='content.report')),
            ],
        ),
        migrations.DeleteModel(
            name='StructuredInsight',
        ),
    ]
