# Generated by Django 4.2 on 2025-05-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_usecasetheme_alter_usecase_company_usecase_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasetheme',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
