# Generated by Django 4.2 on 2025-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_usecasetheme_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='use_case_name',
            field=models.CharField(blank=True, help_text='A clear, concise one-sentence summary of the use case', max_length=1000, null=True),
        ),
    ]
