# Generated by Django 4.2 on 2025-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_usecase_use_case_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='credibility_reasoning',
            field=models.TextField(blank=True, help_text='Explanation of the credibility assessment', null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='credibility_score',
            field=models.IntegerField(blank=True, help_text='Score from 0-10 indicating the credibility of the use case', null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='is_credible',
            field=models.BooleanField(blank=True, help_text='Whether the use case is considered credible', null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='is_relevant',
            field=models.BooleanField(blank=True, help_text='Whether the use case is relevant to user requirements', null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='relevance_reasoning',
            field=models.TextField(blank=True, help_text='Explanation of the relevance assessment', null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='relevance_score',
            field=models.IntegerField(blank=True, help_text='Score from 0-10 indicating the relevance to user requirements', null=True),
        ),
    ]
