# Generated by Django 4.2 on 2025-05-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_usecase_credibility_reasoning_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usecase',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='report',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='content.usecasetheme'),
        ),
    ]
