# Generated by Django 4.2 on 2025-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_alter_usecase_options_report_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='country',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='geography',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='performance_improvement_category',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
