# Generated by Django 4.2 on 2025-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_usecase_country_usecase_geography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasetheme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
