# Generated by Django 4.2 on 2025-06-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_usecasetheme_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usecasetheme',
            options={'ordering': ['-id']},
        ),
    ]
