# Generated by Django 4.2 on 2026-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_alter_prompt_options_alter_usecasetheme_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedsdlcusecase',
            name='report',
        ),
        migrations.RemoveField(
            model_name='extractedusecase',
            name='report',
        ),
        migrations.AddField(
            model_name='usecase',
            name='source_reference',
            field=models.TextField(blank=True, help_text='Reference details (page number, paragraph, URL, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='source_type',
            field=models.CharField(blank=True, choices=[('PDF', 'Uploaded PDF'), ('External Verification', 'External Verification'), ('Web', 'Web Search')], help_text='Type of source for this use case', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ExtractedAISDLCUseCase',
        ),
        migrations.DeleteModel(
            name='ExtractedSDLCUseCase',
        ),
        migrations.DeleteModel(
            name='ExtractedUseCase',
        ),
    ]
