# Generated by Django 4.2 on 2026-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_remove_extractedsdlcusecase_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEntitySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('display_name', models.CharField(help_text='Friendly name for this saved search', max_length=255)),
                ('entity_name', models.CharField(help_text='Name of the company/institution/person', max_length=255)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('university', 'University'), ('research_institution', 'Research Institution'), ('person', 'Person')], default='company', help_text='Type of entity (company, university, research institution, or person)', max_length=30)),
                ('additional_filters', models.JSONField(blank=True, default=dict, help_text='Additional filters (industry, geography, etc.) as JSON', null=True)),
                ('strict_matching', models.BooleanField(default=False, help_text='If True, only show results for the exact entity')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.CharField(blank=True, help_text='User who created this saved search', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Saved Entity Search',
                'verbose_name_plural': 'Saved Entity Searches',
                'ordering': ['-is_favorite', '-usage_count', '-updated_at'],
            },
        ),
    ]
