# Generated by Django 4.2 on 2026-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_usecase_domain_usecase_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='published_date',
            field=models.CharField(blank=True, help_text='Date the source document itself was published/last updated, distinct from use_case_date (the impact date)', max_length=40, null=True),
        ),
    ]
