# Generated by Django 4.2 on 2026-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_usecase_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='affiliation_note',
            field=models.TextField(blank=True, help_text='Statement from this source of when a named researcher joined/left Aston or another institution, if stated', null=True),
        ),
    ]
