# Generated by Django 4.2 on 2025-03-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('prompt', 'Prompt'), ('llm', 'LLM'), ('tool', 'Tool'), ('map', 'Map')], max_length=20),
        ),
    ]
