# Generated by Django 4.2 on 2025-03-18 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_node_id_alter_node_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
